#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:json", "json")
---
apiVersion: v1
kind: Secret
metadata:
  name: educates-frontend-site-config
  namespace: #@ data.values.namespace
type: Opaque
stringData:
  site.json: #@ json.encode(data.values.siteConfig, indent=3)
